### ISSUE TITLE
appium tests don't run on M1 (due to node 12)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1067]
@sosnovsky didn't you run into this issue?

```
[0-11] RUNNING in /Users/tom/git/flowcrypt-ios/appium/FlowCrypt.app - /tests/specs/settings/CheckSettingsForLoggedUser.spec.ts
[0-11] 
<--- Last few GCs --->

[71240:0x128008000]    10130 ms: Scavenge 141.5 (143.8) -> 140.7 (143.8) MB, 0.3 / 0.0 ms  (average mu = 0.993, current mu = 0.977) allocation failure 
[71240:0x128008000]    10164 ms: Scavenge 141.8 (143.8) -> 141.2 (144.3) MB, 0.5 / 0.0 ms  (average mu = 0.993, current mu = 0.977) allocation failure 
[71240:0x128008000]    10331 ms: Scavenge 142.0 (144.3) -> 141.3 (144.6) MB, 0.5 / 0.0 ms  (average mu = 0.993, current mu = 0.977) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x00010fc808d1 <JSObject>
    0: builtin exit frame: new constructor(aka Module)(this=0x0001179ca0d1 <Object map = 0x11208c199>,0x0001179c9da9 <ArrayBuffer map = 0x10fc407f9>,0x0001179ca0d1 <Object map = 0x11208c199>)

    1: ConstructFrame [pc: 0x105718fb8]
    2: StubFrame [pc: 0x105801a64]
    3: sync(aka wasmSync) [0x1123decc1] [/Users/tom/git/flowcrypt-ios/appium/node_modules/@cspotcode/source-map-consumer/lib/wasm....

[0-11] FATAL ERROR: wasm code commit Allocation failed - process out of memory
 1: 0x104f40f44 node::Abort() [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  2: 0x104f410a8 node::OnFatalError(char const*, char const*) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  3: 0x105060e2c v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  4: 0x105060dc0 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  5: 0x1055a02a0 v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(v8::internal::wasm::NativeModule*, unsigned long, v8::base::AddressRegion) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  6: 0x1055a10cc v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegion(unsigned int, v8::base::AddressRegion) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  7: 0x1055a0594 v8::internal::wasm::NativeModule::AddCodeSpace(v8::base::AddressRegion) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  8: 0x1055a0f08 v8::internal::wasm::NativeModule::NativeModule(v8::internal::wasm::WasmEngine*, v8::internal::wasm::WasmFeatures const&, bool, v8::internal::VirtualMemory, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>, std::__1::shared_ptr<v8::internal::Counters>, std::__1::shared_ptr<v8::internal::wasm::NativeModule>*) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  9: 0x1055a3178 v8::internal::wasm::WasmCodeManager::NewNativeModule(v8::internal::wasm::WasmEngine*, v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, unsigned long, bool, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 10: 0x1055a9848 v8::internal::wasm::WasmEngine::NewNativeModule(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, unsigned long, bool, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 11: 0x1055a9788 v8::internal::wasm::WasmEngine::NewNativeModule(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 12: 0x105581134 v8::internal::wasm::CompileToNativeModule(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, v8::internal::wasm::ErrorThrower*, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>, v8::internal::wasm::ModuleWireBytes const&, v8::internal::Handle<v8::internal::FixedArray>*) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 13: 0x1055a7468 v8::internal::wasm::WasmEngine::SyncCompile(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, v8::internal::wasm::ErrorThrower*, v8::internal::wasm::ModuleWireBytes const&) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 14: 0x1055c89c0 v8::(anonymous namespace)::WebAssemblyModule(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 15: 0x1050c5e5c v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 16: 0x1050c51d0 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 17: 0x1050c4cc8 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 18: 0x10579b92c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 19: 0x105718fb8 Builtins_JSBuiltinsConstructStub [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 20: 0x105801a64 Builtins_ConstructHandler [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 21: 0x10571dd80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 22: 0x10571dd80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 23: 0x105718e68 Builtins_JSConstructStubGeneric [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 24: 0x105801a64 Builtins_ConstructHandler [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 25: 0x10571dd80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 26: 0x10571dd80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 27: 0x105716248 Builtins_ArgumentsAdaptorTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 28: 0x105718e38 Builtins_JSConstructStubGeneric [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 29: 0x105801a64 Builtins_ConstructHandler [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 30: 0x10571dd80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 31: 0x10571dd80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 32: 0x10571dd80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 33: 0x10571dd80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 34: 0x10571dd80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 35: 0x10571ae08 Builtins_JSEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 36: 0x10571aaac Builtins_JSEntry [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
37: 0x128008000 
[0-11] RETRYING in /Users/tom/git/flowcrypt-ios/appium/FlowCrypt.app - /tests/specs/settings/CheckSettingsForLoggedUser.spec.ts
[0-11] RUNNING in /Users/tom/git/flowcrypt-ios/appium/FlowCrypt.app - /tests/specs/settings/CheckSettingsForLoggedUser.spec.ts
[0-11] 
<--- Last few GCs --->

[71297:0x158008000]     9938 ms: Scavenge 141.7 (145.1) -> 140.9 (145.1) MB, 0.3 / 0.0 ms  (average mu = 0.998, current mu = 0.987) allocation failure 
[71297:0x158008000]     9971 ms: Scavenge 142.1 (145.1) -> 141.4 (147.6) MB, 0.4 / 0.0 ms  (average mu = 0.998, current mu = 0.987) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x00010f7008d1 <JSObject>
    0: builtin exit frame: new constructor(aka Module)(this=0x0001160ec401 <Object map = 0x10fe2fa09>,0x0001160ec0d9 <ArrayBuffer map = 0x10f6c07f9>,0x0001160ec401 <Object map = 0x10fe2fa09>)

    1: ConstructFrame [pc: 0x1051d4fb8]
    2: StubFrame [pc: 0x1052bda64]
    3: sync(aka wasmSync) [0x1114cc7d9] [/Users/tom/git/flowcrypt-ios/appium/node_modules/@cspotcode/source-map-consumer/lib/wasm....

[0-11] FATAL ERROR: wasm code commit Allocation failed - process out of memory
[0-11]  1: 0x1049fcf44 node::Abort() [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  2: 0x1049fd0a8 node::OnFatalError(char const*, char const*) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  3: 0x104b1ce2c v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  4: 0x104b1cdc0 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  5: 0x10505c2a0 v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(v8::internal::wasm::NativeModule*, unsigned long, v8::base::AddressRegion) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  6: 0x10505d0cc v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegion(unsigned int, v8::base::AddressRegion) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  7: 0x10505c594 v8::internal::wasm::NativeModule::AddCodeSpace(v8::base::AddressRegion) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  8: 0x10505cf08 v8::internal::wasm::NativeModule::NativeModule(v8::internal::wasm::WasmEngine*, v8::internal::wasm::WasmFeatures const&, bool, v8::internal::VirtualMemory, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>, std::__1::shared_ptr<v8::internal::Counters>, std::__1::shared_ptr<v8::internal::wasm::NativeModule>*) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11]  9: 0x10505f178 v8::internal::wasm::WasmCodeManager::NewNativeModule(v8::internal::wasm::WasmEngine*, v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, unsigned long, bool, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 10: 0x105065848 v8::internal::wasm::WasmEngine::NewNativeModule(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, unsigned long, bool, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 11: 0x105065788 v8::internal::wasm::WasmEngine::NewNativeModule(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 12: 0x10503d134 v8::internal::wasm::CompileToNativeModule(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, v8::internal::wasm::ErrorThrower*, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>, v8::internal::wasm::ModuleWireBytes const&, v8::internal::Handle<v8::internal::FixedArray>*) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 13: 0x105063468 v8::internal::wasm::WasmEngine::SyncCompile(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, v8::internal::wasm::ErrorThrower*, v8::internal::wasm::ModuleWireBytes const&) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 14: 0x1050849c0 v8::(anonymous namespace)::WebAssemblyModule(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 15: 0x104b81e5c v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 16: 0x104b811d0 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 17: 0x104b80cc8 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 18: 0x10525792c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 19: 0x1051d4fb8 Builtins_JSBuiltinsConstructStub [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 20: 0x1052bda64 Builtins_ConstructHandler [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 21: 0x1051d9d80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 22: 0x1051d9d80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 23: 0x1051d4e68 Builtins_JSConstructStubGeneric [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 24: 0x1052bda64 Builtins_ConstructHandler [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 25: 0x1051d9d80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 26: 0x1051d9d80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 27: 0x1051d2248 Builtins_ArgumentsAdaptorTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 28: 0x1051d4e38 Builtins_JSConstructStubGeneric [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 29: 0x1052bda64 Builtins_ConstructHandler [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 30: 0x1051d9d80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 31: 0x1051d9d80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 32: 0x1051d9d80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 33: 0x1051d9d80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 34: 0x1051d9d80 Builtins_InterpreterEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 35: 0x1051d6e08 Builtins_JSEntryTrampoline [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
[0-11] 36: 0x1051d6aac Builtins_JSEntry [/Users/tom/.nvm/versions/node/v12.22.7/bin/node]
37: 0x158008000 
[0-11] FAILED in /Users/tom/git/flowcrypt-ios/appium/FlowCrypt.app - /tests/specs/settings/CheckSettingsForLoggedUser.spec.ts (1 retries)

Spec Files:      0 passed, 1 retries, 1 failed, 11 skipped, 12 total (100% completed) in 00:00:37 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flowcrypt-appium@1.0.0 only.test.filter: `wdio ./config/wdio.ios.app.conf.js --suite all --jasmineNodeOpts.grep "user should see public key and should not see private key"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flowcrypt-appium@1.0.0 only.test.filter script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tom/.npm/_logs/2021-11-23T11_26_31_164Z-debug.log
bash-3.2$ 
```

**Comment by tomholub** [comment]
https://stackoverflow.com/questions/65856300/wasm-code-commit-allocation-failed-process-out-of-memory

**Comment by sosnovsky** [comment]
I have node 14 installed locally and don't receive such allocation errors

**Comment by sosnovsky** [comment]
Maybe we can upgrade `node` on A1?

**Comment by tomholub** [comment]
Need to update readme, which says `nvm install 12`. I'm testing node 16.13.0 now. 16 is recommended for A1.

**Comment by sosnovsky** [comment]
I had some issues with `appium` earlier on node 16, that's why I downgraded to `node 14`, but may be it works now

**Comment by tomholub** [comment]
got it - seemed to work ok for me. updated readme in #1043 to use node 16, and in this issue later I'll try the same on CI, so that we are consistent.

**Comment by tomholub** [comment]
Why do I call it A1? It's M1, right? :-)

**Comment by sosnovsky** [comment]
Ah, I thought you mean `A1` machine type on Semaphore 🙂

**Comment by tomholub** [comment]
```
0-2] Error in "COMPOSE EMAIL:  sending message to user with expired/revoked public key produces modal"
Error: Can't call setValue on element with selector "-ios predicate string:type == "XCUIElementTypeTextView"" because element wasn't found
    at async NewMessageScreen.setComposeSecurityMessage (/Users/tom/git/flowcrypt-ios/appium/tests/screenobjects/new-message.screen.ts:87:5)
    at async NewMessageScreen.composeEmail (/Users/tom/git/flowcrypt-ios/appium/tests/screenobjects/new-message.screen.ts:98:5)
    at async UserContext.<anonymous> (/Users/tom/git/flowcrypt-ios/appium/tests/specs/live/composeEmail/SendEmailToRecipientWithExpiredAndRevokedPublicKeys.spec.ts:27:5)

```

send button probably tapped too early
