### ISSUE TITLE
appium doesn't see send button until scrolled down

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1074]
This is interesting - the create email button always hovers in the same space. Why is it needed to scroll down before we can tap it? (in actual app, I don't need to scroll to see/tap the button)

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1065#discussion_r755169995_

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/143046117-c20a9156-e07b-499c-ab1e-07b13e5af6e6.png)

**Comment by ivan-ushakov** [comment]
Possible linked with issue #1079

**Comment by tomholub** [comment]
From my testing, it seemed unrelated. Regardless of loading status, it didn't seem to recognize the send button until I scroll a bit lower. But only if there was more than one page worth of emails (with only a few emails, no problem).

It's as if the additional inbox items obscure the button somehow. Even though visually they don't.

**Comment by tomholub** [comment]
@sosnovsky maybe you would know?

**Comment by tomholub** [comment]
I observed it here: https://flowcrypt.semaphoreci.com/jobs/0026251b-48ef-4b3a-8b8d-1587e778380f

```
[0-2] Screenshot of failed test was saved to /Users/semaphore/git/flowcrypt-ios/appium/tmp 11:55
[0-2] Error in "COMPOSE EMAIL:  user is able to send encrypted email after resetting pass phrase" 11:55
Error: element ("-ios class chain:**/XCUIElementTypeButton[`label == "+"`]") still not displayed after 15000ms 11:55
    at async InboxScreen.checkInboxScreen (/Users/semaphore/git/flowcrypt-ios/appium/tests/screenobjects/inbox.screen.ts:40:5) 11:55
    at async UserContext.<anonymous> (/Users/semaphore/git/flowcrypt-ios/appium/tests/specs/composeEmail/SendEncryptedEmailAfterWrongPassPhrase.spec.ts:41:5) 11:56
[0-2] RETRYING in /Users/semaphore/git/flowcrypt-ios/appium/FlowCrypt.app - /tests/specs/composeEmail/SendEncryptedEmailAfterWrongPassPhrase.spec.ts 12:04
[0-2] RUNNING in /Users/semaphore/git/flowcrypt-ios/appium/FlowCrypt.app - /tests/specs/composeEmail/SendEncryptedEmailAfterWrongPassPhrase.spec.ts 14:11
[0-2] addedRecipientEl value:   demo@flowcrypt.com  14:11
[0-2] Screenshot of failed test was saved to /Users/semaphore/git/flowcrypt-ios/appium/tmp 14:11
[0-2] Error in "COMPOSE EMAIL:  user is able to send encrypted email after resetting pass phrase" 14:11
Error: element ("-ios class chain:**/XCUIElementTypeButton[`label == "+"`]") still not displayed after 15000ms 14:11
    at async InboxScreen.checkInboxScreen (/Users/semaphore/git/flowcrypt-ios/appium/tests/screenobjects/inbox.screen.ts:40:5) 14:11
    at async UserContext.<anonymous> (/Users/semaphore/git/flowcrypt-ios/appium/tests/specs/composeEmail/SendEncryptedEmailAfterWrongPassPhrase.spec.ts:41:5)
```

**Comment by sosnovsky** [comment]
Wasn't able to fix this issue yet, but found that compose button becomes non-accessible after `tableNode.reloadData()` at https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Controllers/Inbox/InboxViewController.swift#L271

Maybe Texture re-renders all views on the screen after `reloadData` and it causes accessibility issues, which are fixed after any gesture (scroll or tap)
Trying to find solution...

**Comment by tomholub** [comment]
Thanks for looking into this! Were you able to reproduce this manually - compose email button not tappable on the first tap of loading inbox, if there are many messages?

**Comment by sosnovsky** [comment]
No, it works well for me in the app, fails only during ui tests

**Comment by tomholub** [comment]
So far, do you think this is fixable (with reasonable effort) ?

**Comment by tomholub** [comment]
Got it. Thanks for looking into it 👍
