### ISSUE TITLE
flaky test: sending message to user without public key produces modal: "Test 1" not displayed

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1153]
```
[iPhone 13 iOS 15.0 #0-2] Spec: /Users/semaphore/git/flowcrypt-ios/appium/tests/specs/composeEmail/SendEmailToRecipientWithoutPublicKey.spec.ts 34:43
[iPhone 13 iOS 15.0 #0-2] Running: iPhone 13 on iOS 15.0 executing /Users/semaphore/git/flowcrypt-ios/appium/FlowCrypt.app 34:43
[iPhone 13 iOS 15.0 #0-2] Session ID: 9fb2341d-e1d8-4a5f-bcd1-64974e49e536 34:43
[iPhone 13 iOS 15.0 #0-2] 34:43
[iPhone 13 iOS 15.0 #0-2] COMPOSE EMAIL: 34:43
[iPhone 13 iOS 15.0 #0-2]    ✖ sending message to user without public key produces modal 34:43
[iPhone 13 iOS 15.0 #0-2] 34:43
[iPhone 13 iOS 15.0 #0-2] 1 failing (1m 26.1s) 34:43
[iPhone 13 iOS 15.0 #0-2] 34:43
[iPhone 13 iOS 15.0 #0-2] 1) COMPOSE EMAIL:  sending message to user without public key produces modal 34:43
[iPhone 13 iOS 15.0 #0-2] Error: element ("-ios class chain:**/XCUIElementTypeTextField[`value == "Test 1"`]") still not displayed after 15000ms 34:43
[iPhone 13 iOS 15.0 #0-2] Error: element ("-ios class chain:**/XCUIElementTypeTextField[`value == "Test 1"`]") still not displayed after 15000ms 34:43
[iPhone 13 iOS 15.0 #0-2]     at async NewMessageScreen.checkFilledComposeEmailInfo (/Users/semaphore/git/flowcrypt-ios/appium/tests/screenobjects/new-message.screen.ts:110:5) 34:43
[iPhone 13 iOS 15.0 #0-2]     at async UserContext.<anonymous> (/Users/semaphore/git/flowcrypt-ios/appium/tests/specs/composeEmail/SendEmailToRecipientWithoutPublicKey.spec.ts:25:5)
```

**Comment by tomholub** [comment]
Encountered here https://flowcrypt.semaphoreci.com/jobs/41f2e187-679b-400b-b6e9-7239335f1788 but passes locally

**Comment by fcvakintos** [comment]
I added sleep 2 seconds before click 'RETURN_BUTTON', it should help

**Comment by tomholub** [comment]
Will you make a separate PR, or was it added in some PR? If so please link it here.

**Comment by fcvakintos** [comment]
will create new one

**Comment by fcvakintos** [comment]
@tomholub https://github.com/FlowCrypt/flowcrypt-ios/pull/1155
