### ISSUE TITLE
flaky test - checking signature/encryption badges

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1164]
```
[0-5] RUNNING in /Users/semaphore/git/flowcrypt-ios/appium/FlowCrypt.app - /tests/specs/live/inbox/CheckAllEmailSignatureCases.spec.ts 18:55
[0-5] Screenshot of failed test was saved to /Users/semaphore/git/flowcrypt-ios/appium/tmp 18:55
[0-5] Error in "INBOX:  user is able to view correct signature badge for all cases" 18:55
Error: element ("~encryptionBadge") still not displayed after 15000ms 18:55
    at runMicrotasks (<anonymous>) 18:55
    at processTicksAndRejections (internal/process/task_queues.js:97:5) 18:55
    at async EmailScreen.checkEncryptionBadge (/Users/semaphore/git/flowcrypt-ios/appium/tests/screenobjects/email.screen.ts:153:5) 19:02
[0-5] RETRYING in /Users/semaphore/git/flowcrypt-ios/appium/FlowCrypt.app - /tests/specs/live/inbox/CheckAllEmailSignatureCases.spec.ts 19:12
[0-5] RUNNING in /Users/semaphore/git/flowcrypt-ios/appium/FlowCrypt.app - /tests/specs/live/inbox/CheckAllEmailSignatureCases.spec.ts 22:59
[0-5] PASSED in /Users/semaphore/git/flowcrypt-ios/appium/FlowCrypt.app - /tests/specs/live/inbox/CheckAllEmailSignatureCases.spec.ts (1 retries) 23:05
```

**Comment by fcvakintos** [comment]
I think we can close this one, I tried to reproduce this issue, but it doesn't appear
