### ISSUE TITLE
expired recipient pubkey test failing on M1

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1177]
```
[0-2] Screenshot of failed test was saved to /Users/tom/git/flowcrypt-ios/appium/tmp
[0-2] Error in "COMPOSE EMAIL:  sending message to user with expired/revoked public key produces modal"
Error: Can't call setValue on element with selector "-ios predicate string:type == "XCUIElementTypeTextView"" because element wasn't found
    at async NewMessageScreen.setComposeSecurityMessage (/Users/tom/git/flowcrypt-ios/appium/tests/screenobjects/new-message.screen.ts:87:5)
    at async NewMessageScreen.composeEmail (/Users/tom/git/flowcrypt-ios/appium/tests/screenobjects/new-message.screen.ts:98:5)
    at async UserContext.<anonymous> (/Users/tom/git/flowcrypt-ios/appium/tests/specs/live/composeEmail/SendEmailToRecipientWithExpiredAndRevokedPublicKeys.spec.ts:27:5)
[0-2] RETRYING in /Users/tom/git/flowcrypt-ios/appium/FlowCrypt.app - /tests/specs/live/composeEmail/SendEmailToRecipientWithExpiredAndRevokedPublicKeys.spec.ts
[0-2] RUNNING in /Users/tom/git/flowcrypt-ios/appium/FlowCrypt.app - /tests/specs/live/composeEmail/SendEmailToRecipientWithExpiredAndRevokedPublicKeys.spec.ts
[0-2] Screenshot of failed test was saved to /Users/tom/git/flowcrypt-ios/appium/tmp
[0-2] Error in "COMPOSE EMAIL:  sending message to user with expired/revoked public key produces modal"
Error: Can't call setValue on element with selector "-ios class chain:**/XCUIElementTypeTextField[`value == "Add Recipient"`]" because element wasn't found
    at async NewMessageScreen.setAddRecipient (/Users/tom/git/flowcrypt-ios/appium/tests/screenobjects/new-message.screen.ts:77:5)
    at async NewMessageScreen.composeEmail (/Users/tom/git/flowcrypt-ios/appium/tests/screenobjects/new-message.screen.ts:96:5)
    at async UserContext.<anonymous> (/Users/tom/git/flowcrypt-ios/appium/tests/specs/live/composeEmail/SendEmailToRecipientWithExpiredAndRevokedPublicKeys.spec.ts:27:5)
[0-2] FAILED in /Users/tom/git/flowcrypt-ios/appium/FlowCrypt.app - /tests/specs/live/composeEmail/SendEmailToRecipientWithExpiredAndRevokedPublicKeys.spec.ts (1 retries)
```

It correctly enters the expired email and renders orange, but no modal shows.

**Comment by fcvakintos** [comment]
i think it resolved - after merging PR for issue #1153

**Comment by tomholub** [comment]
I'm not so sure - that PR was failing tests first time it was submitted, and then the tests were re-run and it passed. Typical flakiness, not resolved. But I'll try.

**Comment by tomholub** [comment]
It did pass now, so something indeed changed.
