### ISSUE TITLE
appium: A session is either terminated or not started

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1214]
https://flowcrypt.semaphoreci.com/jobs/d0635c87-564a-4962-ae55-c01eb7164ff8

```
[0-0] RUNNING in /Users/semaphore/git/flowcrypt-ios/appium/FlowCrypt.app - /tests/specs/live/composeEmail/CheckComposeEmailAfterReopening.spec.ts 01:53
[0-0] /Users/semaphore/git/flowcrypt-ios/appium/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4548 01:53
[0-0]           throw error; 01:53
[0-0]           ^ 01:53
[0-0] 01:53
[0-0] NoSuchDriverError: A session is either terminated or not started 01:53
[0-0]     at asyncHandler (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:243:15) 01:53
[0-0]     at /Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:423:15 01:53
[0-0]     at Layer.handle [as handle_request] (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/express/lib/router/layer.js:95:5) 01:53
[0-0]     at next (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/express/lib/router/route.js:137:13) 01:53
[0-0]     at Route.dispatch (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/express/lib/router/route.js:112:3) 01:53
[0-0]     at Layer.handle [as handle_request] (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/express/lib/router/layer.js:95:5) 01:53
[0-0]     at /Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/express/lib/router/index.js:281:22 01:53
[0-0]     at param (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/express/lib/router/index.js:354:14) 01:53
[0-0]     at param (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/express/lib/router/index.js:365:14) 01:53
[0-0]     at Function.process_params (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/express/lib/router/index.js:410:3) 01:53
[0-0]     at next (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/express/lib/router/index.js:275:10) 01:53
[0-0]     at logger (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/morgan/index.js:144:5) 01:53
[0-0]     at Layer.handle [as handle_request] (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/express/lib/router/layer.js:95:5) 01:53
[0-0]     at trim_prefix (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/express/lib/router/index.js:317:13) 01:53
[0-0]     at /Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/express/lib/router/index.js:284:7 01:53
[0-0]     at Function.process_params (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/appium/node_modules/express/lib/router/index.js:335:12) { 01:53
[0-0]   name: 'invalid session id', 01:53
[0-0]   jasmineMessage: 'Uncaught exception: invalid session id: A session is either terminated or not started' 01:53
[0-0] }
```

**Comment by tomholub** [comment]
@fcvakintos this is currently open / available

**Comment by fcvakintos** [comment]
@tomholub  i cant reproduce it

**Comment by tomholub** [comment]
I understand. It's a flaky issue. But can you research the issue to see what could be possibly causing it, and any workarounds?

**Comment by tomholub** [comment]
ok
