### ISSUE TITLE
Cant run tests locally, get "Could not extract Info.plist from 'FlowCrypt.app':" error

### ISSUE THREAD

**Issue by fcvakintos** [FlowCrypt/flowcrypt-ios#1351]
When I try to run tests, i get error
`Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Could not extract Info.plist from 'FlowCrypt.app': Plist file doesn't exist: '/Users/dmitrysotnikov/workspace/flowcrypt-ios/appium/FlowCrypt.app/Info.plist'
[0-0] 2022-01-31T10:47:45.055Z ERROR webdriver: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not extract Info.plist from 'FlowCrypt.app': Plist file doesn't exist: '/Users/dmitrysotnikov/workspace/flowcrypt-ios/appium/FlowCrypt.app/Info.plist'
[0-0]     at getResponseForW3CError (/Users/dmitrysotnikov/workspace/flowcrypt-ios/appium/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
[0-0]     at asyncHandler (/Users/dmitrysotnikov/workspace/flowcrypt-ios/appium/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)
[0-0] 2022-01-31T10:47:45.056Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] An unknown server-side error occurred while processing the command. Original error: Could not extract Info.plist from 'FlowCrypt.app': Plist file doesn't exist: '/Users/dmitrysotnikov/workspace/flowcrypt-ios/appium/FlowCrypt.app/Info.plist'`

App 
<img width="379" alt="Screenshot 2022-01-31 at 12 57 26" src="https://user-images.githubusercontent.com/91205853/151781848-fea34df9-5e79-4bc8-958a-df3c69f85490.png">

and when I paste new app version in appium directory - I get another error
<img width="1069" alt="Screenshot 2022-01-31 at 12 58 36" src="https://user-images.githubusercontent.com/91205853/151782132-f57703f8-7329-4bc2-b667-82f331c78ae8.png">

**Comment by fcvakintos** [comment]
@tomholub who from devs can help me with this issue?

**Comment by sosnovsky** [comment]
@fcvakintos I just tried to run tests on the latest `master` code - works well for me.
Can you try to delete `FlowCrypt-...` folder from `DerivedData`, then re-build app and copy new `FlowCrypt.app` from `DerivedData/FlowCrypt-...` to `appium` folder?

**Comment by fcvakintos** [comment]
@sosnovsky I cant re-build the app after removing FlowCrypt-...

**Comment by sosnovsky** [comment]
Do you get any error in Xcode?

**Comment by fcvakintos** [comment]
@sosnovsky yes
<img width="1038" alt="Screenshot 2022-01-31 at 15 01 23" src="https://user-images.githubusercontent.com/91205853/151798109-550568b8-042c-4d7b-bbda-301f0db2ebf6.png">
<img width="1040" alt="Screenshot 2022-01-31 at 15 02 05" src="https://user-images.githubusercontent.com/91205853/151798183-767513ed-42e2-4498-bb84-52619e34e72b.png">

**Comment by sosnovsky** [comment]
I see `No space left on device` error in logs there - do you have enough space on your computer?
Are you building on simulator or on real device?

**Comment by fcvakintos** [comment]
on simulator

**Comment by sosnovsky** [comment]
Another possible fix - try to reboot macOS, maybe it'll remove some caches

**Comment by fcvakintos** [comment]
@sosnovsky 
I get these errors after removing FlowCrypt-...
<img width="342" alt="Screenshot 2022-01-31 at 15 56 09" src="https://user-images.githubusercontent.com/91205853/151806468-696e4142-e103-4218-b460-9e32ec989b9b.png">
<img width="341" alt="Screenshot 2022-01-31 at 15 56 15" src="https://user-images.githubusercontent.com/91205853/151806477-277f6af6-3e9f-4eef-bc39-297dc56c513e.png">

**Comment by fcvakintos** [comment]
yes, master

**Comment by fcvakintos** [comment]
it helps, thanks @sosnovsky

**Comment by sosnovsky** [comment]
Great 👍
