### ISSUE TITLE
UI tests failing on Semaphore

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#1352]
UI tests are failing on Semaphore with error

```bash
ios-sim start --devicetypeid com.apple.CoreSimulator.SimDeviceType.iPhone-13 Failed in 
00:02
385.   SyntaxError: Unexpected token u in JSON at position 0 00:02
386    at JSON.parse (<anonymous>) 00:02
387    at Object.list (/Users/semaphore/.nvm/versions/node/v16.13.2/lib/node_modules/ios-sim/node_modules/simctl/simctl.js:171:33) 00:02
388    at getDeviceFromDeviceTypeId (/Users/semaphore/.nvm/versions/node/v16.13.2/lib/node_modules/ios-sim/src/helpers.js:196:21) 00:02
389    at StartCommand.run (/Users/semaphore/.nvm/versions/node/v16.13.2/lib/node_modules/ios-sim/src/commands/start.js:10:20) 00:02
390    at StartCommand._run (/Users/semaphore/.nvm/versions/node/v16.13.2/lib/node_modules/ios-sim/node_modules/@oclif/command/lib/command.js:43:31) 00:02
391    TypeError: Cannot read properties of undefined (reading 'devicetypes')
```

**Comment by sosnovsky** [comment]
Temporary disabled `simctl` on Semaphore - UI tests work well now.

Related issue - https://github.com/ios-control/simctl/issues/30
