### ISSUE TITLE
dep updates - can't build locally anymore

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#555]
Sorry for my lack of experience with the pods/ruby ecosystem.

When I try to build the app, I get:

> The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

pod install:

```
$ pod install
Traceback (most recent call last):
	2: from /usr/local/bin/pod:23:in `<main>'
	1: from /Library/Ruby/Site/2.6.0/rubygems.rb:303:in `activate_bin_path'
/Library/Ruby/Site/2.6.0/rubygems.rb:284:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)
```

```
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin20]
```

I can see that in CI we just run `make dependencies`:

```
$ make dependencies
gem install bundler:2.2.25
Successfully installed bundler-2.2.25
Parsing documentation for bundler-2.2.25
Done installing documentation for bundler after 4 seconds
1 gem installed
bundle config set path 'vendor/bundle'
Your application has set path to "vendor/bundle". This will override the global value you are currently setting
bundle install
Using rake 13.0.6
Using rexml 3.2.5
Using CFPropertyList 3.0.4
Using concurrent-ruby 1.1.9
Using i18n 1.8.10
Using minitest 5.14.4
Using thread_safe 0.3.6
Using tzinfo 1.2.9
Using activesupport 5.2.6
Using public_suffix 4.0.6
Using addressable 2.8.0
Using httpclient 2.8.3
Using json 2.5.1
Using algoliasearch 1.27.5
Using artifactory 3.0.15
Using atomos 0.1.3
Using aws-eventstream 1.2.0
Using aws-partitions 1.505.0
Using aws-sigv4 1.4.0
Using jmespath 1.4.0
Using aws-sdk-core 3.121.0
Using aws-sdk-kms 1.48.0
Using aws-sdk-s3 1.103.0
Using babosa 1.0.4
Using bundler 2.2.25
Using claide 1.0.3
Using fuzzy_match 2.0.4
Using nap 1.1.0
Using netrc 0.11.0
Using ffi 1.15.4
Using ethon 0.14.0
Using typhoeus 1.4.0
Using cocoapods-core 1.10.2
Using cocoapods-deintegrate 1.0.5
Using cocoapods-downloader 1.5.1
Using cocoapods-plugins 1.0.0
Using cocoapods-search 1.0.1
Using cocoapods-trunk 1.6.0
Using cocoapods-try 1.2.0
Using colored2 3.1.2
Using escape 0.0.4
Using fourflusher 2.3.1
Using gh_inspector 1.1.3
Using molinillo 0.6.6
Using ruby-macho 1.4.0
Using nanaimo 0.3.0
Using xcodeproj 1.21.0
Using cocoapods 1.10.2
Using colored 1.2
Using highline 2.0.3
Using commander 4.6.0
Using declarative 0.0.20
Using digest-crc 0.6.4
Using unf_ext 0.0.8
Using unf 0.1.4
Using domain_name 0.5.20190701
Using dotenv 2.7.6
Using emoji_regex 3.2.2
Using excon 0.85.0
Using faraday-em_http 1.0.0
Using faraday-em_synchrony 1.0.0
Using faraday-excon 1.1.0
Using faraday-httpclient 1.0.1
Using faraday-net_http 1.0.1
Using faraday-net_http_persistent 1.2.0
Using faraday-patron 1.0.0
Using faraday-rack 1.0.0
Using multipart-post 2.0.0
Using ruby2_keywords 0.0.5
Using faraday 1.8.0
Using http-cookie 1.0.4
Using faraday-cookie_jar 0.0.7
Using faraday_middleware 1.1.0
Using fastimage 2.2.5
Using jwt 2.2.3
Using memoist 0.16.2
Using multi_json 1.15.0
Using os 1.1.1
Using signet 0.16.0
Using googleauth 0.17.1
Using mini_mime 1.1.1
Using trailblazer-option 0.1.1
Using uber 0.1.0
Using representable 3.1.1
Using retriable 3.1.2
Using webrick 1.7.0
Using google-apis-core 0.4.1
Using google-apis-androidpublisher_v3 0.11.0
Using google-apis-playcustomapp_v1 0.5.0
Using google-apis-iamcredentials_v1 0.7.0
Using google-apis-storage_v1 0.7.0
Using google-cloud-env 1.5.0
Using google-cloud-errors 1.2.0
Using google-cloud-core 1.6.0
Using google-cloud-storage 1.34.1
Using mini_magick 4.11.0
Using naturally 2.2.1
Using optparse 0.1.1
Using plist 3.6.0
Using rubyzip 2.3.2
Using security 0.1.3
Using simctl 1.6.8
Using terminal-notifier 2.0.0
Using unicode-display_width 1.8.0
Using terminal-table 1.8.0
Using tty-screen 0.8.1
Using tty-cursor 0.7.1
Using tty-spinner 0.9.3
Using word_wrap 1.0.0
Using rouge 2.0.7
Using xcpretty 0.3.0
Using xcpretty-travis-formatter 1.0.1
Using fastlane 2.194.0
Using fastlane-plugin-semaphore 0.2.0
Using http-accept 1.7.0
Using mime-types-data 3.2021.0901
Using mime-types 3.3.1
Using rest-client 2.1.0
Using xcode-install 2.8.0
Bundle complete! 5 Gemfile dependencies, 119 gems now installed.
Bundled gems are installed into `./vendor/bundle`
```

But none of the above helped, and unsure how to get over the pod install issue without messing more things up.

What should I do? Thanks!

**Comment by tomholub** [comment]
Looking at the readme, this looks more hopeful:

```
$ bundle exec pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "RealmSwift":
  In snapshot (Podfile.lock):
    RealmSwift (= 10.15.1)

  In Podfile:
    RealmSwift

None of your spec sources contain a spec satisfying the dependencies: `RealmSwift, RealmSwift (= 10.15.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by tomholub** [comment]
may have fixed it with `bundle exec pod install --repo-update`
