### ISSUE TITLE
update appium dependencies

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#803]
From v6.x.x to v7.x.x equivalents, and adjust codebase if needed (in one PR). The updates may contain some stability fixes.

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/6306961/138921625-bc2a73b3-917a-4543-b342-5dbf6badd730.png">

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/769#issuecomment-952110664_

**Comment by tomholub** [comment]
dependabot took care of it

**Comment by fcvakintos** [comment]
@tomholub all tests are failing now, please check https://flowcrypt.semaphoreci.com/jobs/e6ded4b7-caf9-410d-8310-d4d52f4cc5f4 and breaking changes are in master now. I don't think it's a good idea to update all dependencies by using bot and what do we solve by updating these libraries?

**Comment by tomholub** [comment]
The tests passed on each PR that updated a dep, and also each time the change got pushed to master:

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/6306961/139574109-2c0f5e31-acd2-4256-afce-44518904cfa2.png">

The link you linked also passed. What is broken?

**Comment by fcvakintos** [comment]
@tomholub JOB is passed but each test failed by
[0-0] (node:7527) UnhandledPromiseRejectionWarning: TSError: ⨯ Unable to compile TypeScript:00:11
tests/screenobjects/splash.screen.ts(7,7): error TS2451: Cannot redeclare block-scoped variable 'data_1'.00:11
    at createTSError (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/ts-node/src/index.ts:750:12)00:11
    at reportTSError (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/ts-node/src/index.ts:754:19)00:11
    at getOutput (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/ts-node/src/index.ts:941:36)00:11
    at Object.compile (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/ts-node/src/index.ts:1243:30)00:11
    at Module.m._compile (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/ts-node/src/index.ts:1370:30)00:11
    at Module.m._compile (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/ts-node/src/index.ts:1371:23)00:11
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)00:11
    at require.extensions.<computed> (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/ts-node/src/index.ts:1374:12)00:11
    at Object.require.extensions.<computed> [as .ts] (/Users/semaphore/git/flowcrypt-ios/appium/node_modules/ts-node/src/index.ts:1374:12)00:11
    at Module.load (internal/modules/cjs/loader.js:863:32)

Spec Files:	 0 passed, 6 skipped, 6 total (100% completed) in 00:00:29

**Comment by tomholub** [comment]
I see.

**Comment by tomholub** [comment]
It's unfortunate that appium will pass the tests when there's an error in this situation. They should have failed the tests automatically when they got the promise rejections, or the tests should have failed to build and stop there.

Before we fix the dependency problem, can you look into making sure that the tests run with a `--unhandled-rejections=strict` node flag? Without it, it's inherently unsafe. With that, we should see the tests start correctly failing on CI.

After that, we'd either update up (ideally) or revert the updates.

**Comment by tomholub** [comment]
Understood your point about auto-updater - if we cannot do it reliably, then we'll disable it. But in that case you'd have to keep the libs up to date manually. It's part of software development to keep your libraries updated, as I said above, to take advantage of bugfixes they merge in. Unless the library is so crappy that it introduces more bugs in each release than they fix. Hopefully appium is not in that category.

**Comment by fcvakintos** [comment]
I will take care about updates if needed

**Comment by tomholub** [comment]
please do. For now, you can make a PR to revert the package json file to previous form. Separately, I'll see if I can make the tests fail when this happens, should be easy.

**Comment by fcvakintos** [comment]
Let's merge your fix to this branch and test if all good?

**Comment by fcvakintos** [comment]
@tomholub could you merge it or you already merged with other branch?

**Comment by tomholub** [comment]
Yes, I cherry picked the dangling promise commit into the merged branch.

**Comment by fcvakintos** [comment]
@tomholub we can close this ticket?

**Comment by tomholub** [comment]
no - the dependencies have not been updated to latest yet. Can you do it?

**Comment by fcvakintos** [comment]
@tomholub can we close this ticket?

**Comment by tomholub** [comment]
See my comment on the PR https://github.com/FlowCrypt/flowcrypt-ios/pull/964#issuecomment-964056589

**Comment by fcvakintos** [comment]
Tests codebase is ok.

**Comment by tomholub** [comment]
Test codebase will need to be updated to support newer version of the dependencies:

> @wdio/local-runner","@wdio/spec-reporter" and "@wdio/sync"

 Otherwise we will forever be stuck on old versions.

**Comment by fcvakintos** [comment]
@tomholub I updated all dependencies to latest version, will create PR for this
