### ISSUE TITLE
how to extract app crash logs from simulator with appium test

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#890]
getting this on the following PR #854 

```
[debug] [35m[WD Proxy][39m Proxying [POST /element] to [POST http://127.0.0.1:8100/session/B132895F-2FF9-46A4-9358-B7F543AD49E6/element] with body: {"using":"accessibility id","value":"textField"}
[35m[WD Proxy][39m Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.flowcrypt.as.ios.debug' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff203fbbb4 __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff2019ebe7 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff203fb855 -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x000000010aa35823 -[FBSession activeApplication] + 979\n\t4   WebDriverAgentLib                   0x000000010aa39472 +[FBFindElementCommands handleFindElement:] + 242\n\t5   WebDriverAgentLib                   0x000000010a9fc40c -[FBRoute_TargetAction mountRequest:intoResponse:] + 172\n\t6   WebDriverAgentLib                   0x000000010a9e5234 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t7   WebDriverAgentLib                   0x000000010aa1f28d -[RoutingHTTPServer handleRoute:withRequest:response:] + 189\n\t8   W...
[debug] [35m[W3C][39m Matched W3C error code 'invalid element state' to InvalidElementStateError
[debug] [35m[W3C (f44351b2)][39m Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [35m[W3C (f44351b2)][39m     at XCUITestDriver.doNativeFind (/Users/luke/git/flowcrypt-ios/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:130:11)
[debug] [35m[W3C (f44351b2)][39m     at runMicrotasks (<anonymous>)
[debug] [35m[W3C (f44351b2)][39m     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The app in the simulator crashes before this happens. What can I do to retrieve the app crash logs?

**Comment by fcvakintos** [comment]
@tomholub the besxt way is to push crash logs to artifacts as for me

**Comment by tomholub** [comment]
Great. How about locally?

**Comment by fcvakintos** [comment]
@tomholub is it the same task as 891? If yes please close one and leave another

**Comment by tomholub** [comment]
Sort of. One is for regular logs, and one is for crash stack traces / crash reports. Is it the same?

**Comment by fcvakintos** [comment]
could we ask devs?

**Comment by tomholub** [comment]
@ivan-ushakov on iOS, when the app crashes, is there any information that could be retrieved from the app from some other place than just the log output? Something could import into xcode to investigate the crash?

**Comment by ivan-ushakov** [comment]
> @ivan-ushakov on iOS, when the app crashes, is there any information that could be retrieved from the app from some other place than just the log output? Something I could later import into xcode to investigate the crash?

Yes, if simulator crashed with app, you could find crashlog in special place:
```
ls ~/Library/Logs/DiagnosticReports/FlowCrypt_*
/Users/ivan/Library/Logs/DiagnosticReports/FlowCrypt_2021-11-02-103113_Ivans-iMac.crash	/Users/ivan/Library/Logs/DiagnosticReports/FlowCrypt_2021-11-02-103249_Ivans-iMac.crash	/Users/ivan/Library/Logs/DiagnosticReports/FlowCrypt_2021-11-02-223306_Ivans-iMac.crash
/Users/ivan/Library/Logs/DiagnosticReports/FlowCrypt_2021-11-02-103150_Ivans-iMac.crash	/Users/ivan/Library/Logs/DiagnosticReports/FlowCrypt_2021-11-02-103347_Ivans-iMac.crash
```

**Comment by fcvakintos** [comment]
Please review PR
