### ISSUE TITLE
appium: CheckEncryptedEmailAfterRestartApp.spec fails

### ISSUE THREAD

**Issue by ivan-ushakov** [FlowCrypt/flowcrypt-ios#892]
```
[iPhone Simulator iOS 15.0 #0-2] Spec: /Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/inbox/CheckEncryptedEmailAfterRestartApp.spec.ts
[iPhone Simulator iOS 15.0 #0-2] Running: iPhone Simulator on iOS 15.0 executing /Users/ivan/Library/Developer/Xcode/DerivedData/FlowCrypt-dkmvlhcprnebshbeurvkormazmnk/Build/Products/Debug-iphonesimulator/FlowCrypt.app
[iPhone Simulator iOS 15.0 #0-2] Session ID: d2c5e9ca-21f4-420f-870f-54c01607f850
[iPhone Simulator iOS 15.0 #0-2]
[iPhone Simulator iOS 15.0 #0-2] INBOX: 
[iPhone Simulator iOS 15.0 #0-2]    ✖ user is able to see encrypted email with pass phrase after restart app
[iPhone Simulator iOS 15.0 #0-2]
[iPhone Simulator iOS 15.0 #0-2] 1 failing (57.5s)
[iPhone Simulator iOS 15.0 #0-2]
[iPhone Simulator iOS 15.0 #0-2] 1) INBOX:  user is able to see encrypted email with pass phrase after restart app
[iPhone Simulator iOS 15.0 #0-2] Error: element ("~undefined") still not displayed after 15000ms
[iPhone Simulator iOS 15.0 #0-2] Error: element ("~undefined") still not displayed after 15000ms
[iPhone Simulator iOS 15.0 #0-2]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[iPhone Simulator iOS 15.0 #0-2]     at EmailScreen.checkEmailAddress (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/screenobjects/email.screen.ts:42:21)
[iPhone Simulator iOS 15.0 #0-2]     at EmailScreen.checkOpenedEmail (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/screenobjects/email.screen.ts:57:14)
[iPhone Simulator iOS 15.0 #0-2]     at UserContext.<anonymous> (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/inbox/CheckEncryptedEmailAfterRestartApp.spec.ts:27:21)
```

![Simulator Screen Shot - appiumTest-9D7CBD23-6790-436E-926D-CA189C5C5DAC-iPhone X - 2021-11-02 at 10 49 27](https://user-images.githubusercontent.com/1408366/139806641-56af72d7-606e-480d-96ed-5500e0712ccb.png)

**Comment by ivan-ushakov** [comment]
Maybe I have old .env file because I don't have this:
```
sender: {
    email: process.env.SENDER_EMAIL,
}
```

**Comment by ivan-ushakov** [comment]
I tried to add that property to `.env` file but now I get another error:
```
[iPhone Simulator iOS 15.0 #0-2] Spec: /Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/inbox/CheckEncryptedEmailAfterRestartApp.spec.ts
[iPhone Simulator iOS 15.0 #0-2] Running: iPhone Simulator on iOS 15.0 executing /Users/ivan/Library/Developer/Xcode/DerivedData/FlowCrypt-dkmvlhcprnebshbeurvkormazmnk/Build/Products/Debug-iphonesimulator/FlowCrypt.app
[iPhone Simulator iOS 15.0 #0-2] Session ID: 9b89cb6c-cc35-427c-ad1c-bb2776cc19e3
[iPhone Simulator iOS 15.0 #0-2]
[iPhone Simulator iOS 15.0 #0-2] INBOX: 
[iPhone Simulator iOS 15.0 #0-2]    ✖ user is able to see encrypted email with pass phrase after restart app
[iPhone Simulator iOS 15.0 #0-2]
[iPhone Simulator iOS 15.0 #0-2] 1 failing (43.5s)
[iPhone Simulator iOS 15.0 #0-2]
[iPhone Simulator iOS 15.0 #0-2] 1) INBOX:  user is able to see encrypted email with pass phrase after restart app
[iPhone Simulator iOS 15.0 #0-2] invalid argument: Parameters were incorrect. We wanted {"required":[["appId"],["bundleId"]],"optional":["options","sessionId","id"]} and you sent []
[iPhone Simulator iOS 15.0 #0-2]     at <Jasmine>
[iPhone Simulator iOS 15.0 #0-2]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[iPhone Simulator iOS 15.0 #0-2]     at UserContext.<anonymous> (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/inbox/CheckEncryptedEmailAfterRestartApp.spec.ts:29:16)
```

**Comment by tomholub** [comment]
Please remove all non-sensitive values from env file. Then you know for sure.

**Comment by tomholub** [comment]
Sorry, I thought this was @fcvakintos

**Comment by tomholub** [comment]
@ivan-ushakov I'll send you my env file

**Comment by fcvakintos** [comment]
@ivan-ushakov do you need a help from my side?
or issue resolved?

**Comment by ivan-ushakov** [comment]
> @ivan-ushakov do you need a help from my side?
> or issue resolved?


Test still failing:
```
import {
    SplashScreen,
    CreateKeyScreen,
    InboxScreen,
    EmailScreen
} from '../../screenobjects/all-screens';

import {CommonData} from '../../data';

describe('INBOX: ', () => {

    it('user is able to see encrypted email with pass phrase after restart app', () => {

        const senderEmail = CommonData.sender.email;
        const emailSubject = 'encrypted email';
        const emailText = 'test test';
        const wrongPassPhrase = 'user is not able to see email';

        const correctPassPhrase = CommonData.account.passPhrase;

        const bundleId = CommonData.bundleId.id;

        SplashScreen.login();
        CreateKeyScreen.setPassPhrase();

        InboxScreen.clickOnEmailBySubject(emailSubject);
        EmailScreen.checkOpenedEmail(senderEmail, emailSubject, emailText);

        driver.terminateApp(bundleId);

        driver.activateApp(bundleId);

        InboxScreen.clickOnEmailBySubject(emailSubject);

        //try to see encrypted message with wrong pass phrase
        EmailScreen.enterPassPhrase(wrongPassPhrase);
        EmailScreen.clickOkButton();
        EmailScreen.checkWrongPassPhraseErrorMessage();

        //check email after setting correct pass phrase
        EmailScreen.enterPassPhrase(correctPassPhrase);
        EmailScreen.clickSaveButton();
        EmailScreen.checkOpenedEmail(senderEmail, emailSubject, emailText);

        //reopen email without pass phrase
        EmailScreen.clickBackButton();
        InboxScreen.clickOnEmailBySubject(emailSubject);
        EmailScreen.checkOpenedEmail(senderEmail, emailSubject, emailText);
    });
});
```

Output:

```
[iPhone Simulator iOS 15.0 #0-2] Spec: /Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/inbox/CheckEncryptedEmailAfterRestartApp.spec.ts
[iPhone Simulator iOS 15.0 #0-2] Running: iPhone Simulator on iOS 15.0 executing /Users/ivan/Library/Developer/Xcode/DerivedData/FlowCrypt-dkmvlhcprnebshbeurvkormazmnk/Build/Products/Debug-iphonesimulator/FlowCrypt.app
[iPhone Simulator iOS 15.0 #0-2] Session ID: dab09928-0b3a-466d-9b67-193f15911b7a
[iPhone Simulator iOS 15.0 #0-2]
[iPhone Simulator iOS 15.0 #0-2] INBOX: 
[iPhone Simulator iOS 15.0 #0-2]    ✖ user is able to see encrypted email with pass phrase after restart app
[iPhone Simulator iOS 15.0 #0-2]
[iPhone Simulator iOS 15.0 #0-2] 1 failing (55.5s)
[iPhone Simulator iOS 15.0 #0-2]
[iPhone Simulator iOS 15.0 #0-2] 1) INBOX:  user is able to see encrypted email with pass phrase after restart app
[iPhone Simulator iOS 15.0 #0-2] Error: element ("~undefined") still not displayed after 15000ms
[iPhone Simulator iOS 15.0 #0-2] Error: element ("~undefined") still not displayed after 15000ms
[iPhone Simulator iOS 15.0 #0-2]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[iPhone Simulator iOS 15.0 #0-2]     at EmailScreen.checkEmailAddress (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/screenobjects/email.screen.ts:42:21)
[iPhone Simulator iOS 15.0 #0-2]     at EmailScreen.checkOpenedEmail (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/screenobjects/email.screen.ts:57:14)
[iPhone Simulator iOS 15.0 #0-2]     at UserContext.<anonymous> (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/inbox/CheckEncryptedEmailAfterRestartApp.spec.ts:27:21)
```

I guess we get `undefined` because `.env` file does not contain this property `email: process.env.SENDER_EMAIL`

**Comment by ivan-ushakov** [comment]
I just checked and if I add `SENDER_EMAIL` to Tom's `.env` file, I have that test succeed

**Comment by fcvakintos** [comment]
@ivan-ushakov I will send you file by email

**Comment by fcvakintos** [comment]
@ivan-ushakov give me your email

**Comment by fcvakintos** [comment]
@tomholub I propose to send email to all team with new .env file if any updates

**Comment by ivan-ushakov** [comment]
> @ivan-ushakov I will send you file by email

I guess my `.env` file is fine now, but you are right, we need to have actual `.env` file on local machines

**Comment by tomholub** [comment]
> @tomholub I propose to send email to all team with new .env file if any updates

First and foremost, we need to have all non-secret information NOT in the env file. We can't be expected to keep track of the env file on a dayily/weekly basis. It should only contain secrets that don't change often. Everything else goes in the codebase.

**Comment by tomholub** [comment]
> > @ivan-ushakov I will send you file by email
> 
> I guess my `.env` file is fine now, but you are right, we need to have actual `.env` file on local machines

Does that mean the test runs now on your device?

**Comment by ivan-ushakov** [comment]
> > > @ivan-ushakov I will send you file by email
> > 
> > 
> > I guess my `.env` file is fine now, but you are right, we need to have actual `.env` file on local machines
> 
> Does that mean the test runs now on your device?


Yes, I can run this test successfully

**Comment by tomholub** [comment]
thank you both
