### ISSUE TITLE
appium: CheckSettingsForLoggedUser.spec failed

### ISSUE THREAD

**Issue by ivan-ushakov** [FlowCrypt/flowcrypt-ios#895]
Output:

```
[iPhone Simulator iOS 15.0 #0-6] Spec: /Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/settings/CheckSettingsForLoggedUser.spec.ts
[iPhone Simulator iOS 15.0 #0-6] Running: iPhone Simulator on iOS 15.0 executing /Users/ivan/Library/Developer/Xcode/DerivedData/FlowCrypt-dkmvlhcprnebshbeurvkormazmnk/Build/Products/Debug-iphonesimulator/FlowCrypt.app
[iPhone Simulator iOS 15.0 #0-6] Session ID: 964b1378-4733-470c-b903-822fa3e667fe
[iPhone Simulator iOS 15.0 #0-6]
[iPhone Simulator iOS 15.0 #0-6] SETTINGS: 
[iPhone Simulator iOS 15.0 #0-6]    ✖ user should see public key and should not see private key
[iPhone Simulator iOS 15.0 #0-6]
[iPhone Simulator iOS 15.0 #0-6] 1 failing (1m 0.6s)
[iPhone Simulator iOS 15.0 #0-6]
[iPhone Simulator iOS 15.0 #0-6] 1) SETTINGS:  user should see public key and should not see private key
[iPhone Simulator iOS 15.0 #0-6] Error: element ("~Show public key") still not displayed after 15000ms
[iPhone Simulator iOS 15.0 #0-6] Error: element ("~Show public key") still not displayed after 15000ms
[iPhone Simulator iOS 15.0 #0-6]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[iPhone Simulator iOS 15.0 #0-6]     at KeysScreen.checkSelectedKeyScreen (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/screenobjects/keys.screen.ts:79:34)
[iPhone Simulator iOS 15.0 #0-6]     at UserContext.<anonymous> (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/settings/CheckSettingsForLoggedUser.spec.ts:29:20)
```

![Simulator Screen Shot - appiumTest-9D7CBD23-6790-436E-926D-CA189C5C5DAC-iPhone X - 2021-11-02 at 13 46 19](https://user-images.githubusercontent.com/1408366/139833033-e5500ef9-6ea7-479e-a2d0-1c586a7f1243.png)

For some reason we can not read keys from storage

**Comment by tomholub** [comment]
Is this on master?

**Comment by ivan-ushakov** [comment]
> Is this on master?

This happens on `issue-852-no-prv-found` branch

**Comment by tomholub** [comment]
@ivan-ushakov would you want @sosnovsky to debug this further? He has his hands empty now. In fact @sosnovsky I also wanted your review on this PR, it's huge.

**Comment by sosnovsky** [comment]
I compiled app from the latest code of `issue-852-no-prv-found` branch and this test passes there without any issues

<img width="568" alt="Screenshot 2021-11-03 at 00 04 18" src="https://user-images.githubusercontent.com/1062093/139958238-81c2610b-d45f-4ba2-b783-b45d3fe52970.png">

Maybe it was fixed by today's PR code updates?

**Comment by tomholub** [comment]
Yes - Ivan ended up fixing it yesterday in the same PR.
