### ISSUE TITLE
MenuBarScreen.clickMenuIcon not always open menu

### ISSUE THREAD

**Issue by ivan-ushakov** [FlowCrypt/flowcrypt-ios#981]
```
[iPhone Simulator iOS 15.0 #0-1] Spec: /Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/composeEmail/SelectRecipientByName.spec.ts
[iPhone Simulator iOS 15.0 #0-1] Running: iPhone Simulator on iOS 15.0 executing /Users/ivan/Library/Developer/Xcode/DerivedData/FlowCrypt-dkmvlhcprnebshbeurvkormazmnk/Build/Products/Debug-iphonesimulator/FlowCrypt.app
[iPhone Simulator iOS 15.0 #0-1] Session ID: aaaeab87-e4aa-4285-b98d-af3a229328c5
[iPhone Simulator iOS 15.0 #0-1]
[iPhone Simulator iOS 15.0 #0-1] COMPOSE EMAIL: 
[iPhone Simulator iOS 15.0 #0-1]    ✖ user is able to select recipient from contact list using contact name
[iPhone Simulator iOS 15.0 #0-1]
[iPhone Simulator iOS 15.0 #0-1] 1 failing (57.6s)
[iPhone Simulator iOS 15.0 #0-1]
[iPhone Simulator iOS 15.0 #0-1] 1) COMPOSE EMAIL:  user is able to select recipient from contact list using contact name
[iPhone Simulator iOS 15.0 #0-1] Error: element ("~e2e.enterprise.test@flowcrypt.com") still not displayed after 15000ms
[iPhone Simulator iOS 15.0 #0-1] Error: element ("~e2e.enterprise.test@flowcrypt.com") still not displayed after 15000ms
[iPhone Simulator iOS 15.0 #0-1]     at MenuBarScreen.checkUserEmail (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/screenobjects/menu-bar.screen.ts:39:21)
[iPhone Simulator iOS 15.0 #0-1]     at UserContext.<anonymous> (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/composeEmail/SelectRecipientByName.spec.ts:29:23)
```

Sometimes it works fine, sometimes I have to manually click menu icon during the test

**Comment by fcvakintos** [comment]
I will check, do you use real device or emulator?

**Comment by ivan-ushakov** [comment]
> I will check, do you use real device or emulator?

Simulator

**Comment by tomholub** [comment]
I have the same problem. Same for closing menu.
